server:
  port: 8761

spring:
  application:
    name: service-discovery
  security:
    user:
      name: ${EUREKA_USER:test}
      password: ${EUREKA_PASSWORD:test}
  devtools:
    restart:
      enabled: false

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${spring.security.user.name}:${spring.security.user.password}@${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 500000
    wait-time-in-ms-when-sync-empty: 0
    response-cache-update-interval-ms: 5000

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always